model_name: "gpt-3.5-turbo" # gpt-3.5-turbo, gpt-4, claude-3-sonnet-20240229...
deployment_name: "" # azure openai model deployment name, e.g. openai-gpt4
api_type: "chatglm3" # openai, claude, azure, chatglm3
input_file: "tests/test.pdf"
output_file_format: "markdown" # pdf, markdown
source_language: "English"
target_language: "Chinese"