OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "your_openai_api_key"

ClaudeAIModel:
  model: "claude-3-haiku-20240307"
  api_key: "your_claude_api_key"

AzureOpenAIModel:
  model: "deployment-name"
  api_key: "your_openai_api_key"
  api_version: "api_version"
  api_url: "https://your-azure-openai-endpoint"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"